#!/usr/bin/env node

//this hook creates the platforms folder

var fs = require('fs');

fs.mkdirSync('platforms', '0775', function(err) {
  if (err && err.code != 'EEXIST') {
    console.log(err);
    throw new Error(err);
  }
});
